# Generated by Django 3.1.1 on 2020-11-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('language', models.CharField(choices=[('en-IN', 'Urdu'), ('en-US', 'English')], default='en-IN', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.CharField(blank=True, max_length=500, null=True)),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.upload')),
            ],
        ),
    ]
